plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

title: The Turing Game
description: Here I will analyze the underlying ideas of the broad class of games that the 'parlor game' described by Mr. Turing as well as the same game with a modification that he proposed belong to. 
